# Generated by Django 5.2.9 on 2025-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfiles', '0003_alter_customuser_id_alter_savedfile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedfile',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='savedfile',
            name='user',
        ),
        migrations.AddField(
            model_name='savedfile',
            name='uid',
            field=models.IntegerField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
