# Generated by Django 5.2.9 on 2025-12-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfiles', '0004_remove_savedfile_file_data_remove_savedfile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfile',
            name='uid',
            field=models.CharField(unique=True),
        ),
    ]
